name: features

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - name: Start dev start
        run: |
          nohup npm run start &
          sleep 5
      - name: Debug with curl
        run: curl -v -X GET http://localhost:3000
      - name: Run feature tests
        run: npm run features
